# Generated by Django 4.2.21 on 2025-06-05 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
        ('MainAddress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field_Education_School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=30, verbose_name='نام رشته تحصیلی')),
            ],
            options={
                'verbose_name_plural': 'رشته های تحصیلی مدرسه ',
                'db_table': 'Field_Education_School',
            },
        ),
        migrations.CreateModel(
            name='SchoolInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100, verbose_name='نام مدرسه')),
                ('logo', models.FileField(blank=True, null=True, upload_to='SchoolInformation', verbose_name='لوگوی مدرسه')),
                ('status', models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('rejected', 'rejected')], default='pending', max_length=20, null=True, verbose_name='آیا مدرسه مورد تایید میباشد ؟ ')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainAddress.province', verbose_name='آدرس')),
                ('manager', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.managerinformation', verbose_name='مدیر مدرسه')),
            ],
            options={
                'verbose_name_plural': 'اطلاعات مدرسه ها',
                'db_table': 'SchoolInformation',
            },
        ),
        migrations.CreateModel(
            name='Level_Education_School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_level', models.CharField(max_length=100, verbose_name='نام سطح تحصیلی')),
                ('education_fields', models.ManyToManyField(null=True, related_name='levels', to='school.field_education_school', verbose_name='رشته\u200cهای تحصیلی')),
                ('school', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.schoolinformation')),
            ],
            options={
                'verbose_name_plural': 'سطح تحصیلی مدارس',
                'db_table': 'Level_Education_School',
            },
        ),
        migrations.AddField(
            model_name='field_education_school',
            name='level_education_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.level_education_school'),
        ),
    ]
