# Generated by Django 4.2.21 on 2025-06-01 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
        ('MainAddress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=100, verbose_name='نام مدرسه')),
                ('logo', models.FileField(blank=True, null=True, upload_to='SchoolInformation', verbose_name='لوگوی مدرسه')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainAddress.province', verbose_name='آدرس')),
                ('manager', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.managerinformation', verbose_name='مدیر مدرسه')),
            ],
            options={
                'verbose_name_plural': 'اطلاعات مدرسه ها',
                'db_table': 'SchoolInformation',
            },
        ),
    ]
