# Generated by Django 4.2.21 on 2025-06-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level_Education_School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_level', models.CharField(max_length=100, verbose_name='سطح تحصیلی مدارس')),
            ],
            options={
                'verbose_name_plural': 'سطح تحصیلی مدارس',
                'db_table': 'Level_Education_School',
            },
        ),
    ]
