# Generated by Django 4.2.21 on 2025-06-02 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_level_education_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='level_education_school',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.schoolinformation', verbose_name='مدرسه'),
        ),
    ]
