# Generated by Django 4.2.21 on 2025-06-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_level_education_school_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field_Education_School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=30, verbose_name='نام رشته تحصیلی')),
            ],
            options={
                'verbose_name_plural': 'رشته های تحصیلی مدرسه ',
                'db_table': 'Field_Education_School',
            },
        ),
        migrations.AddField(
            model_name='level_education_school',
            name='fields',
            field=models.ManyToManyField(to='school.field_education_school'),
        ),
    ]
