# Generated by Django 4.2.21 on 2025-06-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_field_education_school_level_education_school_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level_education_school',
            name='fields',
            field=models.ManyToManyField(to='school.field_education_school', verbose_name='رشته های تحصیلی'),
        ),
    ]
