# Generated by Django 4.2.21 on 2025-06-04 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_level_education_school_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level_education_school',
            name='fields',
        ),
        migrations.AddField(
            model_name='field_education_school',
            name='level_education_school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.level_education_school'),
        ),
        migrations.AddField(
            model_name='level_education_school',
            name='education_fields',
            field=models.ManyToManyField(null=True, related_name='levels', to='school.field_education_school', verbose_name='رشته\u200cهای تحصیلی'),
        ),
        migrations.AlterField(
            model_name='level_education_school',
            name='name_level',
            field=models.CharField(max_length=100, verbose_name='نام سطح تحصیلی'),
        ),
        migrations.AlterField(
            model_name='level_education_school',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.schoolinformation'),
        ),
    ]
