# Generated by Django 4.2.21 on 2025-06-05 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_remove_level_education_school_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolinformation',
            name='approved',
            field=models.BooleanField(default=False, null=True, verbose_name='آیا مدرسه مورد تایید میباشد ؟ '),
        ),
    ]
