# Generated by Django 4.2.21 on 2025-06-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_schoolinformation_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolinformation',
            name='approved',
        ),
        migrations.AddField(
            model_name='schoolinformation',
            name='status',
            field=models.CharField(choices=[('approved', 'approved'), ('pending', 'pending'), ('rejected', 'rejected')], default='pending', max_length=20, null=True, verbose_name='آیا مدرسه مورد تایید میباشد ؟ '),
        ),
    ]
