# Generated by Django 4.2.21 on 2025-06-05 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainAddress', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number1', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('phone_number2', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس')),
                ('address2', models.TextField(verbose_name='جزئیات منزل')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainAddress.province', verbose_name='آدرس')),
                ('client_manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name_plural': 'مشخصات مدیران',
                'db_table': 'ManagerInformation',
            },
        ),
        migrations.CreateModel(
            name='DocumentManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc1', models.FileField(upload_to='DocumentManager/', verbose_name='سند 1 احراز هویت کاربری ')),
                ('doc2', models.FileField(upload_to='DocumentManager/', verbose_name='سند 2 احراز هویت کاربری ')),
                ('doc3', models.FileField(upload_to='DocumentManager/', verbose_name='سند 3 احراز هویت کاربری ')),
                ('doc4', models.FileField(upload_to='DocumentManager/', verbose_name='سند 4 احراز هویت کاربری ')),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='manager.managerinformation')),
            ],
            options={
                'verbose_name_plural': 'سند احراز هویت مدیران',
                'db_table': 'DocumentManager',
            },
        ),
    ]
