# Generated by Django 4.2.21 on 2025-06-05 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام سال تحصیلی')),
                ('start', models.DateField(verbose_name='شروع سال تحصیلی')),
                ('end', models.DateField(verbose_name='پایان سال تحصیلی')),
            ],
            options={
                'verbose_name_plural': 'سال تحصیلی',
                'db_table': 'AcademicYear',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Academic.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_period', models.CharField(choices=[('KH', 'خرداد'), ('SH', 'شهریور'), ('DI', 'دی')], default='KH', max_length=2, verbose_name='دوره امتحانی')),
                ('passed', models.BooleanField(verbose_name='آیا قبول شده؟')),
                ('exam_date', models.DateField(verbose_name='تاریخ امتحان')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academic.enrollment', verbose_name='ثبت\u200cنام')),
            ],
            options={
                'verbose_name_plural': 'نتایج امتحان',
                'db_table': 'ExamResult',
            },
        ),
    ]
