# Generated by Django 4.2.21 on 2025-06-02 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='filed',
            new_name='field',
        ),
    ]
