# Generated by Django 4.2.21 on 2025-06-05 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('school', '0001_initial'),
        ('Academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.field_education_school'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.level_education_school'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentinformation'),
        ),
    ]
