# Generated by Django 4.2.21 on 2025-06-04 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_remove_level_education_school_fields_and_more'),
        ('student', '0002_document_authenticate_student_status_document_authentication'),
        ('Academic', '0002_rename_filed_enrollment_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enrollment',
            options={},
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Academic.academicyear'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.field_education_school'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.level_education_school'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentinformation'),
        ),
        migrations.AlterModelTable(
            name='enrollment',
            table=None,
        ),
    ]
