# Generated by Django 4.2.21 on 2025-06-01 21:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MainAddress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس')),
                ('status', models.CharField(choices=[('no_check', 'no_check'), ('approved', 'approved'), ('failed', 'failed')], default='no_check', max_length=15, verbose_name='وضعیت  احراز هویت ')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainAddress.province', verbose_name='آدرس')),
                ('client_student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='دانش آموز')),
            ],
            options={
                'verbose_name_plural': 'اطلاعات هویتی دانش آموزان',
                'db_table': 'StudentInformation',
            },
        ),
        migrations.CreateModel(
            name='Document_Education_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file1', models.FileField(blank=True, null=True, upload_to='Document_Education_Student', verbose_name='مدرک تحصیلی پایه 1 ')),
                ('file2', models.FileField(blank=True, null=True, upload_to='Document_Education_Student', verbose_name='مدرک تحصیلی پایه 2 ')),
                ('file3', models.FileField(blank=True, null=True, upload_to='Document_Education_Student', verbose_name='مدرک تحصیلی پایه 3 ')),
                ('file4', models.FileField(blank=True, null=True, upload_to='Document_Education_Student', verbose_name='مدرک تحصیلی پایه 4 ')),
                ('file5', models.FileField(blank=True, null=True, upload_to='Document_Education_Student', verbose_name='مدرک تحصیلی پایه 5 ')),
                ('file6', models.FileField(blank=True, null=True, upload_to='Document_Education_Student', verbose_name='مدرک تحصیلی پایه 6 ')),
                ('file7', models.FileField(blank=True, null=True, upload_to='Document_Education_Student', verbose_name='مدرک تحصیلی پایه 7 ')),
                ('file8', models.FileField(blank=True, null=True, upload_to='Document_Education_Student', verbose_name='مدرک تحصیلی پایه 8 ')),
                ('file9', models.FileField(blank=True, null=True, upload_to='Document_Education_Student', verbose_name='9 ')),
                ('file10', models.FileField(blank=True, null=True, upload_to='Document_Education_Student', verbose_name='مدرک تحصیلی پایه 10 ')),
                ('file11', models.FileField(blank=True, null=True, upload_to='Document_Education_Student', verbose_name='مدرک تحصیلی پایه 11 ')),
                ('file12', models.FileField(blank=True, null=True, upload_to='Document_Education_Student', verbose_name='12 ')),
                ('status_document_education', models.CharField(choices=[('no_check', 'no_check'), ('approved', 'approved'), ('failed', 'failed')], default='no_check', max_length=15, verbose_name='وضعیت مدارک تحصیلی')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.studentinformation', verbose_name='دانش آموز')),
            ],
            options={
                'verbose_name_plural': 'مدارک تحصیلی دانش آموزان',
                'db_table': 'Document_Education_Student',
            },
        ),
        migrations.CreateModel(
            name='Document_Authenticate_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc1', models.FileField(upload_to='DocumentStudent', verbose_name='مدرک هویتی 1 ')),
                ('doc2', models.FileField(upload_to='DocumentStudent', verbose_name='مدرک هویتی 2 ')),
                ('doc3', models.FileField(upload_to='DocumentStudent', verbose_name='مدرک هویتی 3 ')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.studentinformation', verbose_name='دانش آموز')),
            ],
            options={
                'verbose_name_plural': 'مدارک هویتی دانش آموزان',
                'db_table': 'Document_Authenticate_Student',
            },
        ),
    ]
