# Generated by Django 4.2.21 on 2025-06-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_authenticate_student',
            name='status_document_authentication',
            field=models.CharField(choices=[('no_check', 'no_check'), ('approved', 'approved'), ('failed', 'failed')], default='no_check', max_length=15, null=True, verbose_name='وضعیت مدارک هویتی'),
        ),
    ]
