# Generated by Django 4.2.21 on 2025-06-05 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_country', models.CharField(max_length=20, verbose_name='نام کشور')),
            ],
            options={
                'verbose_name_plural': 'کشورها',
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_province', models.CharField(max_length=20, verbose_name='نام استان')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainAddress.country', verbose_name='کشور')),
            ],
            options={
                'verbose_name_plural': 'استان ها',
                'db_table': 'Province',
            },
        ),
    ]
