# Generated by Django 4.2.21 on 2025-06-05 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان پیام')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('status', models.CharField(choices=[('no_check', 'در انتظار بررسی'), ('checking', 'در حال بررسی'), ('answered', 'پاسخ داده شده')], default='no_check', max_length=12, verbose_name='وضعیت تیکت')),
                ('user_type', models.CharField(choices=[('manager', 'مدیر'), ('student', 'دانش\u200cآموز')], default='student', max_length=10)),
                ('reply', models.TextField(blank=True, null=True, verbose_name='پاسخ مدیر/ادمین')),
                ('client_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر تیکت')),
            ],
            options={
                'verbose_name_plural': 'تیکت\u200cهای دریافتی',
                'db_table': 'TicketInformation',
            },
        ),
    ]
