# Generated by Django 4.2.21 on 2025-06-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketinformation',
            name='reply',
            field=models.TextField(blank=True, null=True, verbose_name='پاسخ مدیر/ادمین'),
        ),
        migrations.AlterField(
            model_name='ticketinformation',
            name='status',
            field=models.CharField(choices=[('no_check', 'در انتظار بررسی'), ('checking', 'در حال بررسی'), ('answered', 'پاسخ داده شده')], default='no_check', max_length=12, verbose_name='وضعیت تیکت'),
        ),
        migrations.AlterField(
            model_name='ticketinformation',
            name='user_type',
            field=models.CharField(choices=[('manager', 'مدیر'), ('student', 'دانش\u200cآموز')], default='student', max_length=10),
        ),
    ]
